spring:
  cache:
    expiration: ${SPRING_CACHE_EXPIRATION:3600000}
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://class-teacher:class-teacher@localhost:27017/class-teacher?authSource=admin}
      authentication-database: admin

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASSWORD:class-teacher}
    database: ${REDIS_DATABASE:0}

server:
  port: ${APPLICATION_PORT:3000}

manager:
  SECRETARY_USER: ${MANAGER_SECRETARY_USER:secretary}
  SECRETARY_PASSWORD: ${MANAGER_SECRETARY_PASSWORD:secretary}

jwt:
  salt: ${JWT_SALT:salt}
  expiration: ${JWT_EXPIRATION:3600000}
  insurer: ${JWT_INSURER:ClassTeacher}
  token_key: ${JTW_TOKEN_KEY:qwertyuiopasdfghjklzxcvbnm123456}