spring:
  data:
    mongodb:
      uri: mongodb://class-teacher:class-teacher@localhost:27017/class-teacher?authSource=admin
      host: localhost
      port: 27017
      password: class-teacher
      username: class-teacher
      database: class-teacher
      authentication-database: admin

  redis:
    host: redis
    port: 6379
    password: class-teacher
basic:
  salt: class-teacher
  server:
    port: 8081
manager:
  SECRETARY_USER: andrey
  SECRETARY_PASSWORD: andrey

jwt:
  expiration: 604800000
  insurer: class-teacher
  token_key: qwertyuiopasdfghjklzxcvbnm123456