spring:
  cache:
    type: redis
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://class-teacher:class-teacher@localhost:27017/class-teacher?authSource=admin}
      authentication-database: admin

  redis:
    uri: ${REDIS_URI:redis://class-teacher:class-teacher@localhost:6379/0}

manager:
  SECRETARY_USER: ${MANAGER_SECRETARY_USER:secretary}
  SECRETARY_PASSWORD: ${MANAGER_SECRETARY_PASSWORD:secretary}

jwt:
  salt: ${JWT_SALT:salt}
  expiration: ${JWT_EXPIRATION:3600000}
  insurer: ${JWT_INSURER:ClassTeacher}
  token_key: ${JTW_TOKEN_KEY:qwertyuiopasdfghjklzxcvbnm123456}