spring:
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://class-teacher:class-teacher@localhost:27017/class-teacher?authSource=admin
      embedded:
        version: 3.0.1
  redis:
    host: redis
    port: 6379
    password: class-teacher
basic:
  salt: class-teacher
  server:
    port: 8081

